//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipment()
        {
            this.checkout_records = new HashSet<checkout_records>();
            this.waitlists = new HashSet<waitlist>();
        }
    
        public int equip_id { get; set; }
        public string equip_type { get; set; }
        public string equip_title { get; set; }
        public string equip_director { get; set; }
        public string equip_genre { get; set; }
        public Nullable<int> equip_length { get; set; }
        public Nullable<System.DateTime> last_checkout { get; set; }
        public Nullable<System.DateTime> last_return { get; set; }
        public Nullable<int> last_transaction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<checkout_records> checkout_records { get; set; }
        public virtual checkout_records checkout_records1 { get; set; }
        public virtual checkout_records checkout_records2 { get; set; }
        public virtual checkout_records checkout_records3 { get; set; }
        public virtual checkout_records checkout_records4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<waitlist> waitlists { get; set; }
    }
}
