//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryDBEntities : DbContext
    {
        public LibraryDBEntities()
            : base("name=LibraryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<audio> audios { get; set; }
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<checkout_records> checkout_records { get; set; }
        public virtual DbSet<equipment> equipments { get; set; }
        public virtual DbSet<fee> fees { get; set; }
        public virtual DbSet<movie> movies { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<waitlist> waitlists { get; set; }
        public virtual DbSet<objects> objects { get; set; }
        public virtual DbSet<objects_type> objects_type { get; set; }
    }
}
