//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movie()
        {
            this.checkout_records = new HashSet<checkout_records>();
            this.waitlists = new HashSet<waitlist>();
            this.waitlists1 = new HashSet<waitlist>();
        }
    
        public int movie_id { get; set; }
        public string movie_type { get; set; }
        public string movie_title { get; set; }
        public string movie_director { get; set; }
        public string movie_genre { get; set; }
        public Nullable<int> movie_length { get; set; }
        public Nullable<System.DateTime> last_checkout { get; set; }
        public Nullable<System.DateTime> last_return { get; set; }
        public Nullable<int> last_transaction { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<checkout_records> checkout_records { get; set; }
        public virtual checkout_records checkout_records1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<waitlist> waitlists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<waitlist> waitlists1 { get; set; }
    }
}
