//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class objects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public objects()
        {
            this.checkout_records = new HashSet<checkout_records>();
        }
    
        public int object_id { get; set; }
        public Nullable<int> object_type { get; set; }
        public string object_title { get; set; }
        public string object_author { get; set; }
        public string object_medium { get; set; }
        public string object_genre { get; set; }
        public Nullable<int> object_length { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<checkout_records> checkout_records { get; set; }
        public virtual objects_type objects_type { get; set; }
    }
}
