//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class waitlist
    {
        public int list_id { get; set; }
        public int list_item_id { get; set; }
        public int object_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime create_date { get; set; }
    
        public virtual audio audio { get; set; }
        public virtual audio audio1 { get; set; }
        public virtual book book { get; set; }
        public virtual book book1 { get; set; }
        public virtual equipment equipment { get; set; }
        public virtual movie movie { get; set; }
        public virtual movie movie1 { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual user user2 { get; set; }
        public virtual user user3 { get; set; }
    }
}
